#!/bin/bash

# The first argument is the task type (e.g. BUILD or QA)
# If it is not BUILD, then the SONARSOURCE_QA environment variable is set to true
# This has an effect if the pom.xml contains the following snippet:
# <project...>
# ...
#   <profiles>
#     <profile>
#       <id>qa</id>
#       <activation>
#         <property>
#           <name>env.SONARSOURCE_QA</name>
#           <value>true</value>
#         </property>
#       </activation>
#      ...
#     </profile>
#   </profiles>
# </project>
# This usually changes the way the project is built.

set +o verbose
set -euo pipefail

# generic environment variables used by Gradle build
export GIT_SHA1=$CIRRUS_CHANGE_IN_REPO
export GITHUB_BASE_BRANCH=${CIRRUS_BASE_BRANCH:-}
export GITHUB_BRANCH=$CIRRUS_BRANCH
export GITHUB_REPO=${CIRRUS_REPO_FULL_NAME}
export PROJECT=${CIRRUS_REPO_NAME}
export PULL_REQUEST=${CIRRUS_PR:-false}
export PULL_REQUEST_SHA=${CIRRUS_BASE_SHA:-}
export PIPELINE_ID=${CIRRUS_BUILD_ID}

export LANG=C.UTF-8

TASK_TYPE=$1
if [[ "$TASK_TYPE" != "BUILD"* ]]; then
  export SONARSOURCE_QA=true
fi

: "${CI_BUILD_NUMBER?missing parameter. See https://xtranet-sonarsource.atlassian.net/wiki/spaces/RE/pages/2992210934}"
BUILD_NUMBER=${CI_BUILD_NUMBER}
BUILD_ID=${CI_BUILD_NUMBER}
echo "BUILD_NUMBER: $BUILD_NUMBER"
export BUILD_NUMBER BUILD_ID

if [[ "${GITHUB_TOKEN:-}" == "ENCRYPTED"* ]]; then
  echo "Unsetting GITHUB_TOKEN"
  unset GITHUB_TOKEN
fi

M2_SOURCE=~/.m2
if [[ -f "/c/buildTools-docker/mvn/settings-public-auth.xml" ]]; then
  # /c/buildTools-docker/mvn is populated during Windows image creation
  M2_SOURCE=/c/buildTools-docker/mvn
fi

[[ ! -d ~/.m2 ]] && mkdir ~/.m2
if [[ "${TASK_TYPE}" == *"-PRIVATE" || "${TASK_TYPE}" == "QA"* || "${TASK_TYPE}" == "PROMOTE"* ]]; then
  cp "${M2_SOURCE}/settings-private.xml" ~/.m2/settings.xml
else
  if [[ -n "${ARTIFACTORY_ACCESS_TOKEN:-}" ]]; then
    cp "${M2_SOURCE}/settings-public-auth.xml" ~/.m2/settings.xml
  else
    echo "No ARTIFACTORY_ACCESS_TOKEN found, Repox will not be accessible".
  fi
fi

case $BUILD_ID in
    ''|*[!0-9]*) echo "$BUILD_ID is not a number" && exit 1 ;;
esac
set -o verbose
