#!/bin/bash

set -euo pipefail

# Required environment variables
: "${ARTIFACTORY_URL?Environment variable missing}"
: "${ARTIFACTORY_DEPLOY_ACCESS_TOKEN?Environment variable missing}"

jfrog config remove repox > /dev/null 2>&1 # Do not log if the repox config were not present
jfrog config add repox --artifactory-url "$ARTIFACTORY_URL" --access-token "$ARTIFACTORY_DEPLOY_ACCESS_TOKEN"

jfrog_npm_publish() {

  local repo_resolve=${1:-npm}
  local repo_deploy=${2:-sonarsource-npm-public-qa}
  local build_name=${3:-$CIRRUS_REPO_NAME}
  local build_number=${4:-$BUILD_NUMBER}


  jfrog npm-config --repo-resolve "$repo_resolve" --repo-deploy "$repo_deploy"
  jfrog npm publish --build-name="$build_name" --build-number="$build_number"
  jfrog rt build-publish "$build_name" "$build_number"
}
