repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: 40f924cd642f5dc98d12bd97b07f3752223553da  # frozen: v0.1.30
    hooks:
      - id: shellcheck
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 8e756eb1aa6a741a2c80b37e0795c7c29104fa6d  # frozen: 43.239.0
    hooks:
      - id: renovate-config-validator
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 8ef330cbb7204d388aa7a620f9549bcea8009663  # frozen: 0.37.3
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: a4d5d37e66ebcd6b3705204a1d6dbb56dea66338  # frozen: v0.49.0
    hooks:
      - id: markdownlint
