repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9 # v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: d0bcdb35c6999a4a120b528f050d2b11778fd3d0 # v0.1.23
    hooks:
      - id: shellcheck
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 4a2fbe3c2f8e5831b4967bbb32ce80abf5381815 # 38.114.0
    hooks:
      - id: renovate-config-validator
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: b4235fda059c7c36722a3f8c4b71c45a0826a8b7 # 0.29.3
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: aa975a18c9a869648007d33864034dbc7481fe5e # v0.42.0
    hooks:
      - id: markdownlint
