#!/bin/bash

set -euo pipefail

source "$(dirname "$0")"/includes/git_utils
source "$(dirname "$0")"/includes/version_util
source analyze

# source npm_deploy
source npm_version_utils


if is_master_branch && ! is_pull_request; then
  echo "On master branch and not a pull request."

  git fetch origin "${GITHUB_BRANCH}"
  echo "Fetched origin ${GITHUB_BRANCH}."

  CURRENT_VERSION=$(get_current_version)
  echo "Current version: $CURRENT_VERSION"

  # set_npm_version_with_build_id "$BUILD_NUMBER"
  echo "Set npm version with build ID: $BUILD_NUMBER."

  check_version_format "$PROJECT_VERSION"
  echo "Checked version format: $PROJECT_VERSION."

  echo "Installing npm dependencies..."
  npm ci

  echo "Running tests..."
  npm test

  echo "Running Sonar Scanner..."
  run_sonar_scanner \
      -Dsonar.projectVersion="$CURRENT_VERSION"

  echo "Building project..."
  npm run build

  echo "Publishing to JFrog..."
  jfrog_npm_publish

elif is_maintenance_branch && not_pull_request; then
  git fetch origin "${GITHUB_BRANCH}"

  CURRENT_VERSION=$(get_current_version)

  if [[ $CURRENT_VERSION =~ "-SNAPSHOT" ]]; then
    echo "======= Found SNAPSHOT version ======="
    # Do not deploy a SNAPSHOT version but the release version related to this build
    set_npm_version_with_build_id "$BUILD_NUMBER"
    check_version_format "$CURRENT_VERSION"
  else
    echo "======= Found RELEASE version ======="
    echo "======= Deploy $CURRENT_VERSION ======="
    check_version_format "$CURRENT_VERSION"
  fi

  npm ci
  npm test
  run_sonar_scanner \
      -Dsonar.branch.name="$GITHUB_BRANCH"

  npm run build
  jfrog_npm_publish

elif is_pull_request; then
  # Do not deploy a SNAPSHOT version but the release version related to this build and PR
  set_npm_version_with_build_id "$BUILD_NUMBER"

  if [ "${DEPLOY_PULL_REQUEST:-}" == "true" ]; then
    echo '======= with deploy ======='

    check_version_format "$PROJECT_VERSION"

    npm ci

    npm test
    run_sonar_scanner \
      -Dsonar.analysis.prNumber="$PULL_REQUEST"

    npm run build
    jfrog_npm_publish

  else
    echo '======= no deploy ======='

    npm ci

    run_sonar_scanner \
      -Dsonar.analysis.prNumber="$PULL_REQUEST"

    npm run build
  fi

elif is_dogfood_branch && not_pull_request; then
  echo '======= Build dogfood branch ======='

  CURRENT_VERSION=$(get_current_version)

  set_npm_version_with_build_id "$BUILD_NUMBER"
  check_version_format "$PROJECT_VERSION"

  npm ci
  npm run build
  jfrog_npm_publish

elif is_long_lived_feature_branch && not_pull_request; then
  npm ci

  npm test
  run_sonar_scanner \
      -Dsonar.branch.name="$GITHUB_BRANCH"

  npm run build

else
  npm ci
  npm test
  npm run build
fi
