#!/bin/bash
# Promote Repox NPM artifact, notify GitHub
# shellcheck source=/dev/null

set -euo pipefail

echo ">> Promote NPM build"
source cirrus-env PROMOTE
source .cirrus/scripts/set_npm_build_version "$BUILD_NUMBER"
cirrus_jfrog_promote

if [ "${GITHUB_TOKEN+x}" ]; then
  echo "GITHUB_TOKEN is provided, will create a commit status in GitHub with build number $BUILD_NUMBER"
  github-notify-promotion
else
  echo "GITHUB_TOKEN is not set (skip the creation of a commit status containing the build number)"
fi
