#!/bin/bash
# This script is responsible to provide functions to give advices to end users.
# If during the execution of a re-ci-images base scripts some errors occurs, then some advices might be given
# in order to assist the user to resolve them (when possible).
#
# WARN: Please do not use this script out of  re-ci-images base bash scripts.
# (using it in another context might break in future releases)
#
# Usage: source includes/cirrus_error_advices

# Requires the environment variables:
# none are required yet the functions are able to autofix

function is_using_cirrus(){
  [ "${CIRRUS_CI:-false}" == "true" ]
}

# CIRRUS_REPO_NAME is provided out of the box by Cirrus CI
function print_invalid_github_token_for_cirrus_advice(){
    REPOSITORY_SHORTNAME=${CIRRUS_REPO_NAME:-"REPOSITORY_NAME"}
   echo "Tips:"
   cat <<EOF

  1) Check the Hashicorp Vault policy for this repository in

    https://github.com/SonarSource/re-terraform-aws-vault/tree/master/orders

    The policy of this repository should contains the following declarations:

    $REPOSITORY_SHORTNAME
      secrets:
        github:
          presets: [default]
          customs:
            - <<: *github_promotion
              repositories: [$REPOSITORY_SHORTNAME]

    and

    github_promotion: &github_promotion
      organization: SonarSource
      suffix: promotion
      description: add a github check containing the build version to the current commit (required by cirrus_promote_maven)
      permissions: {statuses: write}

  2) Check the .cirrus.yml file:

    The token should be declared this way:

    GITHUB_TOKEN: VAULT[development/github/token/\${CIRRUS_REPO_OWNER}-\${CIRRUS_REPO_NAME}-promotion token]
  "
EOF
}
