---
name: Releasability Status
"on":
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches:
      - master
      - dogfood-*
      - branch-*
  push:
    branches:
      - feat/mmatuszny/*

jobs:
  releasability-status:
    name: Releasability status
    runs-on: github-ubuntu-latest-s
    permissions:
      id-token: write
      statuses: write
      contents: read
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: SonarSource/gh-action_releasability/releasability-status@master  # dogfood
        env:
          GITHUB_TOKEN: ${{ github.token }}

  slack-notifications:
    if: always()
    runs-on: github-ubuntu-latest-s
    permissions:
      id-token: write
    steps:
      - name: Vault Secrets
        id: secrets
        uses: SonarSource/vault-action-wrapper@320bd31b03e5dacaac6be51bbbb15adf7caccc32  # v3.1.0
        with:
          secrets: |
            development/kv/data/slack token | SLACK_BOT_TOKEN;
            
      - name: Slack Notification rtCamp
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TOKEN: >-
            ${{ fromJSON(steps.secrets.outputs.vault).SLACK_BOT_TOKEN }}
          SLACK_CHANNEL: test-notifs
          SLACK_TITLE: Build Failed
          SLACK_MESSAGE: |
            Workflow failed in ${{ github.repository }} 🚨
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Branch: ${{ github.event.workflow_run.head_branch }}
            
          SLACK_USERNAME: BuildBot
          SLACK_COLOR: danger
