name: Release sonar-dummy-js

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version'
        required: false

jobs:
  releaseasing:
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@feat/smarini/BUILD-6483-addPublishToNpmJsWorkflow
    with:
      publishToNpmJS: true
      skipJavascriptReleasabilityChecks: false
    permissions:
      id-token: write
      contents: write
