on: 
  release:
    types:
      - published

jobs:  
  publish:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event.release.tag_name }}
      REPOX_URL: "https://repox.jfrog.io/artifactory"
      NPM_REPOSITORY: "sonarsource-npm-public"
      SCOPE: "%40sonarsource/"
      PACKAGE: "sonar-dummy-js"
    steps:            
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
      - uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # tag=v1
        with:
          node-version: 10      
      - name: Download artifacts        
        run: curl -o $PACKAGE-$RELEASE_TAG.tgz $REPOX_URL/$NPM_REPOSITORY/$SCOPE$PACKAGE/-/$SCOPE$PACKAGE-$RELEASE_TAG.tgz
      - run: mv .github/workflows/.npmrc ~/.npmrc 
      - name: Publish npm package            
        env:
          NPM_TOKEN: ${{ secrets.SONARTECH_NPM_TOKEN }}
        run: npm publish $PACKAGE-$RELEASE_TAG.tgz
