name: release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version'
        required: false

jobs:
  release:
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@6172b763888e34a9c21d6ef0eb4a424578d376cb # 5.9.4
    with:
      publishToNpmJS: true
      skipJavascriptReleasabilityChecks: true
    permissions:
      id-token: write
      contents: write
