name: release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version'
        required: false

jobs:
  release:
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@feature/BUILD-10930-npm-trusted-publisher
    with:
      publishToNpmJS: true
      skipJavascriptReleasabilityChecks: true
      useNpmTrustedPublisher: true
    permissions:
      id-token: write
      contents: write
