on: 
  release:
    types:
      - published

jobs:  
  publish:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event.release.tag_name }}
      REPOX_URL: "https://repox.jfrog.io/artifactory"
      NPM_REPOSITORY: "sonarsource-npm-public"
      SCOPE: "%40sonarsource/"
      PACKAGE: "sonar-dummy-js"
    steps:            
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a # tag=v3
        with:
          node-version: 10      
      - name: Download artifacts        
        run: curl -o $PACKAGE-$RELEASE_TAG.tgz $REPOX_URL/$NPM_REPOSITORY/$SCOPE$PACKAGE/-/$SCOPE$PACKAGE-$RELEASE_TAG.tgz
      - run: mv .github/workflows/.npmrc ~/.npmrc 
      - name: Publish npm package            
        env:
          NPM_TOKEN: ${{ secrets.SONARTECH_NPM_TOKEN }}
        run: npm publish $PACKAGE-$RELEASE_TAG.tgz
