on: 
  release:
    types:
      - published

jobs:  
  publish:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event.release.tag_name }}
      REPOX_URL: "https://repox.jfrog.io/artifactory"
      NPM_REPOSITORY: "sonarsource-npm-public"
      SCOPE: "%40sonarsource/"
      PACKAGE: "sonar-dummy-js"
      VAULT_ADDR: https://vault.sonar.build:8200
    permissions:
      id-token: write
      contents: read
    steps:       
      - name: Vault Secrets
        uses: hashicorp/vault-action@cb841f2c86fb6d07cff94fda240828c1abc5ba43 # v2.7.3
        with:
          url: ${{ env.VAULT_ADDR }}
          method: jwt
          path: jwt-ghwf
          role: github-sonarsource-sonar-dummy-js
          secrets: |
            development/kv/data/npmjs sonartech_npm_token | SONARTECH_NPM_TOKEN;
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 10      
      - name: Download artifacts        
        run: curl -o $PACKAGE-$RELEASE_TAG.tgz $REPOX_URL/$NPM_REPOSITORY/$SCOPE$PACKAGE/-/$SCOPE$PACKAGE-$RELEASE_TAG.tgz
      - run: mv .github/workflows/.npmrc ~/.npmrc 
      - name: Publish npm package            
        env:
          NPM_TOKEN: ${{ env.SONARTECH_NPM_TOKEN }}
        run: npm publish $PACKAGE-$RELEASE_TAG.tgz
