name: release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version'
        required: false

jobs:
  release:
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@fix/smarini/BUILD-6483-fixNpmJsVersion # TODO: change this to the new released version
    with:
      publishToNpmJS: true
      skipJavascriptReleasabilityChecks: false
    permissions:
      id-token: write
      contents: write
