on: 
  release:
    types:
      - published

jobs:  
  publish:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event.release.tag_name }}
      NPM_REPOSITORY: "sonarsource-npm-public"
      SCOPE: "%40sonarsource/"
      PACKAGE: "sonar-dummy-js"
    permissions:
      id-token: write
      contents: read
    steps:
      - name: get secrets
        id: secrets
        uses: SonarSource/vault-action-wrapper@7160b50d75c02fe48eb3c8d354ca4fd7029f546a # tag=2.5.0-4
        with:
          secrets: |
            development/kv/data/npmjs sonartech_npm_token | sonartech_npm_token;
            development/kv/data/repox url | repox_url;
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version: 10      
      - name: Download artifacts        
        run: curl -o $PACKAGE-$RELEASE_TAG.tgz $REPOX_URL/$NPM_REPOSITORY/$SCOPE$PACKAGE/-/$SCOPE$PACKAGE-$RELEASE_TAG.tgz
      - run: mv .github/workflows/.npmrc ~/.npmrc 
      - name: Publish npm package            
        env:
          REPOX_URL: ${{ fromJSON(steps.secrets.outputs.vault).repox_url }}
          NPM_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).sonartech_npm_token }}
        run: npm publish $PACKAGE-$RELEASE_TAG.tgz
