on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Release npm package      
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: curl --version
      - run: npm publish
          env:
            NPM_TOKEN: ${{ secrets.SONARTECH_NPM_TOKEN }}
      
      