name: release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version'
        required: false

jobs:
  release:
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@fca2592e48279cb3d31da5f9984d32ed41d5b174 # 6.6.1
    with:
      publishToNpmJS: true
      skipJavascriptReleasabilityChecks: true
      useNpmTrustedPublisher: true
    permissions:
      id-token: write
      contents: write
