---
name: Slack Notifications
on:
 check_run:
  types: [rerequested, completed]

jobs:
 slack-notifications:
  permissions:
   id-token: write  # to authenticate via OIDC
  uses: SonarSource/gh-action_build-notify/.github/workflows/main.yaml@4e96c8adc61581df626865d0be22396c7014c7c3 # 2.1.0
  with:
   slackChannel: squad-dev-infra-github
