---
name: Slack Notifications
on:
  check_suite:
    types: [completed]

permissions:
  contents: read
  checks: read
  id-token: write

jobs:
  slack-notifications:
    if: >-
      contains(fromJSON('["main", "master"]'), github.event.check_suite.head_branch) || startsWith(github.event.check_suite.head_branch, 'dogfood-') || startsWith(github.event.check_suite.head_branch, 'branch-')
    runs-on: github-ubuntu-latest-s
    steps:
      - name: Send Slack Notification
        env:
          GITHUB_TOKEN: ${{ github.token }}
        uses: SonarSource/gh-action_slack-notify@6bcc9bb4734508f44da717ceefaae7c05818093b # 1.0.1
        with:
          slackChannel: squad-dev-infra-github
