name: Unified Dogfooding scans
on:
  schedule:
    # Run the workflow every day at 04:00 UTC
    - cron: '0 4 * * *'
  workflow_dispatch:

env:
  CACHE_BACKEND: s3   # forces S3 for all cache steps, including those in reusable actions

jobs:
  build:
    runs-on: github-ubuntu-latest-s
    name: Build and run shadow scans
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: SonarSource/ci-github-actions/build-npm@master # dogfood
        with:
          run-shadow-scans: true
          artifactory-deploy-repo: sonarsource-npm-public-qa
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer
      - name: Run IRIS Analysis
        uses: SonarSource/unified-dogfooding-actions/run-iris@v1
        with:
          primary_project_key: "SonarSource_sonar-dummy-js"
          primary_platform: "SQC-EU"
          shadow1_project_key: "SonarSource_sonar-dummy-js"
          shadow1_platform: "Next"
          shadow2_project_key: "SonarSource_sonar-dummy-js"
          shadow2_platform: "SQC-US"
